## YAML Template.
---
server:
    port: 8765
spring:
    applicaton:
        name: eureka-feign-client
eureka:
    client:
        serviceURL:
            defaultZone: http://localhost:8761/eureka/
feign:
    hystrix:
        enabled: true