## YAML Template.
---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 9411
spring:
    application:
        name: zipkin-server
    sleuth:
        enabled: false
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest