## YAML Template.
---
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8763
spring:
    application:
        name: eureka-client-one
management:
    security:
        enabled: false  
logging:
    file: "logs/eureka-client-one.log"