## YAML Template.
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
    port: 5000
spring:
    application:
        name: gateway-service
    sleuth:
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
hystrix: 
    command: 
        default: 
            execution: 
                isolation: 
                    thread: 
                        timeoutInMilliseconds: 60000 
ribbon: 
    ReadTimeout: 60000
    ConnectTimeout: 60000

zuul:
    routes:
        api-a:
            path: /user-api/**
            serviceId: user-service
    host: 
        connect-timeout-millis: 10000 
        socket-timeout-millis: 60000